spring.datasource1.driver-class-name=org.postgresql.Driver
spring.datasource1.jdbc-url=jdbc:postgresql://localhost:5433/postgres
spring.datasource1.username=postgres
spring.datasource1.password=postgres
#spring.datasource1.auto-commit=false
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100
